# icons from iconfinder.com, flaticon.com, fontawesome.com

creditcard = "https://cdn2.iconfinder.com/data/icons/free-simple-line-mix/48/5-Credit_Card-128.png"
creditcardsuccess = "https://cdn2.iconfinder.com/data/icons/free-simple-line-mix/48/16-Credit_Card-128.png"
moneybag = "https://cdn4.iconfinder.com/data/icons/finance-and-banking-free/64/Finance_saving-128.png"
piggybank = "https://cdn4.iconfinder.com/data/icons/success-filloutline/64/save-money-coin-piggy_bank-deposit-256.png"
bank = "https://cdn4.iconfinder.com/data/icons/banking-and-finance/500/bank-building-128.png"
wallet = "https://cdn3.iconfinder.com/data/icons/shopping-and-retail-15/512/Wallet-256.png"
startline = "https://image.flaticon.com/icons/png/128/3105/3105659.png"
skills = "https://cdn4.iconfinder.com/data/icons/for-your-interface-free-samples/128/Columns-128.png"
tools = "https://cdn0.iconfinder.com/data/icons/kameleon-free-pack-rounded/110/Settings-5-128.png"
settingsblack = "https://cdn3.iconfinder.com/data/icons/web-ui-3/128/Settings-3-128.png"
settingsblue = "https://cdn4.iconfinder.com/data/icons/web-ui-color/128/Settings-128.png"
bonus = "https://image.flaticon.com/icons/png/128/536/536089.png"
ticket = "https://cdn3.iconfinder.com/data/icons/shopping-and-retail-15/512/Ticket-256.png"
bet = "https://image.flaticon.com/icons/png/128/1232/1232342.png"
warnblue = "https://cdn1.iconfinder.com/data/icons/hawcons/32/700144-icon-61-warning-256.png"
warnyellow = "https://cdn4.iconfinder.com/data/icons/the-weather-is-nice-today/64/weather_48-256.png"
info = "https://cdn4.iconfinder.com/data/icons/Isloo_icons_by_IconFinder/128/info.png"
mining = "https://cdn0.iconfinder.com/data/icons/energy-free/32/Energy_Energy_Coal_Cart_Mining_Fuel-128.png"
thief = "https://cdn2.iconfinder.com/data/icons/user-23/128/User_Cybercriminal.png"
cathiss = "https://cdn2.iconfinder.com/data/icons/cat-power/128/cat_hiss.png"
goldcoin = "https://cdn3.iconfinder.com/data/icons/finance-152/64/24-128.png"
trophy = "https://cdn0.iconfinder.com/data/icons/sport-achievment-badges/128/sport_badges-05-128.png"
fail = "https://cdn3.iconfinder.com/data/icons/ose/Warning.png"
raceflag = "https://image.flaticon.com/icons/png/128/1531/1531222.png"
